.PHONY: clean All

All:
	@echo "----------Building project:[ Cards - Debug ]----------"
	@cd "Cards" && "$(MAKE)" -f  "Cards.mk"
clean:
	@echo "----------Cleaning project:[ Cards - Debug ]----------"
	@cd "Cards" && "$(MAKE)" -f  "Cards.mk" clean
